name: Skip github actions when no added files or changed in app/check folder

on:
  push:
    branches: ['main']

jobs:
  try-skip-if-empty:
#    if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.added, 'app/check') || contains(github.event.head_commit.modified, 'app/check')) }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes
        id: check_changes
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          echo "::set-output name=changed_files::$changed_files"

      - name: Skip if no changes
        if: ${{ steps.check_changes.outputs.changed_files != '' && contains(steps.check_changes.outputs.changed_files, 'app/check') }}
        run: echo "Skipping job because there are no changes in app/check"
        continue-on-error: true # Додаємо `continue-on-error: true`, щоб запобігти виходу з робочого процесу у випадку пропуску завдання

      - name: Run test
        run: |
          echo "toJson(github.event.head_commit.[modified|added|remove])"
          echo "${{ toJson(github.event.head_commit.modified) }}"
          echo "${{ toJson(github.event.head_commit.added) }}"
          echo "${{ toJson(github.event.head_commit.remove) }}"
          
          echo "toJson(github.event.head_commit)"
          echo "${{ toJson(github.event.head_commit) }}"
          
          echo "contains(github.event.head_commit.[added|remove|modified], 'app/check')"
          echo "${{ contains(github.event.head_commit.added, 'app/check') }}"
          echo "${{ contains(github.event.head_commit.remove, 'app/check') }}"
          echo "${{ contains(github.event.head_commit.modified, 'app/check') }}"
          
          echo "condition"
          echo "${{ github.event_name == 'push' && (contains(github.event.head_commit.added, 'app/check') || contains(github.event.head_commit.modified, 'app/check')) == false }}"
          
          echo "Github"
          echo "${{ github }}"