name: Skip github actions when no added files or changed in app/check folder

on:
  push:
    branches: ['main']

jobs:
  try-skip-if-empty:
    if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.added, 'app/check') || contains(github.event.head_commit.modified, 'app/check')) == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test
        run: |
          echo "toJson(github.event.head_commit.[modified|added|remove])"
          echo "${{ toJson(github.event.head_commit.modified) }}"
          echo "${{ toJson(github.event.head_commit.added) }}"
          echo "${{ toJson(github.event.head_commit.remove) }}"
          
          echo "toJson(github.event.head_commit)"
          echo "${{ toJson(github.event.head_commit) }}"
          
          echo "contains(github.event.head_commit.[added|remove|modified], 'app/check')"
          echo "${{ contains(github.event.head_commit.added, 'app/check') }}"
          echo "${{ contains(github.event.head_commit.remove, 'app/check') }}"
          echo "${{ contains(github.event.head_commit.modified, 'app/check') }}"
          
          echo "condition"
          echo "${{ github.event_name == 'push' && (contains(github.event.head_commit.added, 'app/check') || contains(github.event.head_commit.modified, 'app/check')) == false }}"